services:
  structurizr:
    image: structurizr/lite
    ports:
      - "8080:8080"
    volumes:
      - ./docs:/usr/local/structurizr

  patient-service:
    build: 
      context: .
      dockerfile: PatientService/Dockerfile
    ports:
      - "6000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=BloodPressureTracker;User=root;Password=password
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  measurement-service:
    build: 
      context: .
      dockerfile: MeasurementService/Dockerfile
    ports:
      - "6001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=BloodPressureTracker;User=root;Password=password
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: BloodPressureTracker
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db-data:

networks:
  backend:
    driver: bridge